# Generated by Django 4.2.1 on 2023-05-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='img_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
